
package com.example.vehicles.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HelloResourceService", targetNamespace = "http://api.vehicles.example.com/", wsdlLocation = "http://localhost:8085//HelloResourceService?wsdl")
public class HelloResourceService
    extends Service
{

    private final static URL HELLORESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLORESOURCESERVICE_EXCEPTION;
    private final static QName HELLORESOURCESERVICE_QNAME = new QName("http://api.vehicles.example.com/", "HelloResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085//HelloResourceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLORESOURCESERVICE_WSDL_LOCATION = url;
        HELLORESOURCESERVICE_EXCEPTION = e;
    }

    public HelloResourceService() {
        super(__getWsdlLocation(), HELLORESOURCESERVICE_QNAME);
    }

    public HelloResourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLORESOURCESERVICE_QNAME, features);
    }

    public HelloResourceService(URL wsdlLocation) {
        super(wsdlLocation, HELLORESOURCESERVICE_QNAME);
    }

    public HelloResourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLORESOURCESERVICE_QNAME, features);
    }

    public HelloResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloResource
     */
    @WebEndpoint(name = "HelloResourcePort")
    public HelloResource getHelloResourcePort() {
        return super.getPort(new QName("http://api.vehicles.example.com/", "HelloResourcePort"), HelloResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloResource
     */
    @WebEndpoint(name = "HelloResourcePort")
    public HelloResource getHelloResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.vehicles.example.com/", "HelloResourcePort"), HelloResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLORESOURCESERVICE_EXCEPTION!= null) {
            throw HELLORESOURCESERVICE_EXCEPTION;
        }
        return HELLORESOURCESERVICE_WSDL_LOCATION;
    }

}
